# Using a basic Ubuntu image as base
FROM ubuntu:20.04

# Setting up environment
ENV DEBIAN_FRONTEND=noninteractive
ENV MIBS ALL

# Updating and installing necessary packages
RUN apt-get update && apt-get install -y snmp snmp-mibs-downloader

# Set the MIBS environment variable

# run snmpwald
# CMD snmpwalk -v 3 -u authOnlyUser -a MD5 -A tosendpass -x DES -X tocryptpass -l authPriv agent 1.3.6

# Run snmpwalk in a loop
# CMD while true; do snmpwalk -v 3 -u authOnlyUser -a MD5 -A tosendpass -x DES -X tocryptpass -l authPriv agent 1.3.6; sleep 60; done

# Run the SNMP walk
# CMD ["snmpwalk", "-v", "2c", "-c", "public", "agent", "1.3.6"]# # Run snmpget for sysUpTime in a loop
# CMD while true; do snmpget -v 3 -u authOnlyUser -a MD5 -A tosendpass -x DES -X tocryptpass -l authPriv agent 1.3.6.1.2.1.1.3.0; sleep 60; done